services:
  postgres:
    image: postgres:16
    container_name: quest-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quest_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
